openapi: 3.0.3
info:
  version: 1.0.0
  title: SHARK - StnReg connector
  description: Transitional layer
tags:
- name: stnreg_connector
paths:
  /getid:
    get:
      operationId: app.get_id
      tags:
      - post_station
      description: Return a json with year_id as string
      parameters:
        - $ref: '#/components/parameters/timestamp'
        - $ref: '#/components/parameters/shipc'
        - $ref: '#/components/parameters/east'
        - $ref: '#/components/parameters/north'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SharkId'
        404:
          description: Not found
components:
  schemas:
    SharkId:
      type: object
      properties:
        id:
          type: string
          example: 2022_156
        info:
          type: string
          example: success
  parameters:
    timestamp:
      in: query
      name: timestamp
      schema:
        type: string
        example: 2022-01-15 16:35
    shipc:
      in: query
      name: shipc
      schema:
        type: string
        example: 77SE
    east:
      in: query
      name: east
      schema:
        type: number
        format: float
        example: 314572.34
    north:
      in: query
      name: north
      schema:
        type: number
        format: float
        example: 6397858.356